### ISSUE TITLE
Feature request : configuration cells

### ISSUE THREAD

**Issue by traiansf** [LucianCumpata/K-VSCode#3]
Since we use XML syntax for cells, it would be nice for the plugin to take advantage of that.
Some things it could do would be to color/bold the tags, and maybe have a way to match them as happens with parenthesis.

**Comment by LucianCumpata** [comment]
If I understand correctly it should be exactly like in XML?

**Comment by traiansf** [comment]
Yes, it could be, but it should not be very contrasting, as for us tags are not so important as for xml.

Even nicer would be to have different colors for different tags.  There was an approach in IntelliJ Idea (Denis Bogdanas) to use the color elements in the configuration declaration tags to color the tags.

**Comment by LucianCumpata** [comment]
Introduced tags highlighting. Now tags have their own special colour and also their font are bold and italic at the same time. At the moment tags support any combination of letters and digits. Whitespaces will break colorization.
