### ISSUE TITLE
Why is rule orange?

### ISSUE THREAD

**Issue by traiansf** [LucianCumpata/K-VSCode#4]
I would say rule should be the same as the other keywords inside a module, i.e., like context and syntax, and imports.

Of course, this is a matter of debate, but I would like at least to know your arguments for having rule the same color as module/endmodule.

**Comment by LucianCumpata** [comment]
Good question!  I wanted to be different than syntax, but being the same colour as module/endmodule isn't such a great idea.
I'm not familiar with all K keywords and from what group they belong to.
I guess I'll make it the same as syntax,context etc.
